FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu18.04

RUN apt update -y 
RUN apt install -y curl ca-certificates vim sudo git bzip2 libx11-6 wget zip \
    tar unzip gcc tmux make 
    
RUN rm -rf /var/lib/apt/lists/*

RUN apt install -y --reinstall build-essential
RUN apt update -y 
RUN apt install -y libboost-dev libfuse-dev libcurl4-openssl-dev
RUN apt install -y libxml2-dev pkg-config libssl-dev mime-support automake  \
    libtool lsb-release ffmpeg libsm6 libxext6

# Create a working directory.
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it.
RUN adduser --disabled-password --gecos '' --shell /bin/bash user  \
    && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory.
ENV HOME=/home/user
RUN chmod 777 /home/user

# install Miniconda
RUN curl -so ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV PATH=/home/user/miniconda/bin:$PATH

# Set up conda environment
COPY --chown=user msr.yml /app/msr.yml
RUN conda create -n msr python=3.8 numpy && conda env update -f /app/msr.yml; 

ENV CONDA_DEFAULT_ENV=msr
ENV CONDA_PREFIX=/home/user/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH

# I am including this in case it's needed, but at the moment I'm using the host's Nvidia drivers.
# RUN apt update 
# RUN sudo apt install && sudo apt install -y module-init-tools
# RUN sudo apt install linux-headers-4.4.0-1122-aws
# RUN wget https://us.download.nvidia.com/tesla/440.118.02/NVIDIA-Linux-x86_64-440.118.02.run
# RUN sudo bash NVIDIA-Linux-x86_64-440.118.02.run -s


WORKDIR /home/user

USER root

## Install S3 Fuse
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

# RUN conda install -c conda-forge awscli
RUN rm -rf /usr/src/s3fs-fuse
RUN git clone https://github.com/s3fs-fuse/s3fs-fuse/ /usr/src/s3fs-fuse
WORKDIR /usr/src/s3fs-fuse 
RUN ./autogen.sh && ./configure && make && make install
RUN apt install fuse